version: 2.1
orbs:
  barkendeploy: navikt/barkendeploy@dev:master
jobs:
  build_jar:
    docker:
      - image: "circleci/openjdk:11-jdk"
    steps:
      - checkout
      - setup_remote_docker
      - barkendeploy/init
      - barkendeploy/gradle-cache-restore
#      - run:
#          name: Run tests
#          command: ./gradlew test
      - run:
          name: Build jar file
          command: ./gradlew shadowJar -x test
      - barkendeploy/gradle-cache-persist
      - run:
          name: Build and publish Docker image
          command: docker build -t docker.pkg.github.com/navikt/application/${CIRCLE_PROJECT_REPONAME}:${IMAGE_VERSION} .
      - run:
          name: Push docker image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin docker.pkg.github.com
            docker push docker.pkg.github.com/navikt/${CIRCLE_PROJECT_REPONAME}/application:${IMAGE_VERSION}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_jar:
          context: barkendeploy
          filters:
            branches:
              only: master
      - barkendeploy/deploy-publish:
          cluster: dev-fss
          context: barkendeploy
          requires:
            - build_jar
          filters:
            branches:
              only: master
